dataset: mot

train_split: mot17_train_cross_val_frame_0_0_to_0_5_coco
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: data/MOT17
mot_path_val: data/MOT17

#resume: models/crowdhuman_cswinbackbone_deformable_multi_frame_hpc/checkpoint_epoch_80.pth
#resume: models/crowdhuman_motr_v1_hpc/checkpoint_epoch_80.pth
resume: models/crowdhuman_deformable_multi_frame_beast/checkpoint_epoch_80.pth

epochs: 40
lr_drop: 10